version: "3.5"

services:
  validator1:
    image: odinprotocol/core:latest
    container_name: validator1
    networks:
      bandchain:
        ipv4_address: 172.18.0.11
    command: sh -c "chmod +x ./run.sh && ./run.sh validator1"
    volumes:
      - ./genesis.json:/genesis.json

  validator2:
    container_name: validator2
    image: odinprotocol/core:latest
    networks:
      bandchain:
        ipv4_address: 172.18.0.12
    command: sh -c "chmod +x ./run.sh && ./run.sh validator2"
    volumes:
      - ./genesis.json:/genesis.json

  validator3:
    container_name: validator3
    image: odinprotocol/core:latest
    networks:
      bandchain:
        ipv4_address: 172.18.0.13
    command: sh -c "chmod +x ./run.sh && ./run.sh validator3"
    volumes:
      - ./genesis.json:/genesis.json

  validator4:
    container_name: validator4
    image: odinprotocol/core:latest
    networks:
      bandchain:
        ipv4_address: 172.18.0.14
    command: sh -c "chmod +x ./run.sh && ./run.sh validator4"
    volumes:
      - ./genesis.json:/genesis.json

  query-node:
    image: odinprotocol/core:latest
    ports:
      - 26657:26657
    networks:
      bandchain:
        ipv4_address: 172.18.0.15
    command: sh -c "chmod +x ./run.sh && ./run.sh query-node"
    volumes:
      - ./genesis.json:/genesis.json

  rest-server:
    image: odinprotocol/core:latest
    networks:
      bandchain:
        ipv4_address: 172.18.0.20
    restart: always
    ports:
      - 1317:1317
    command: bandcli rest-server --laddr tcp://0.0.0.0:1317 --node tcp://172.18.0.15:26657 --chain-id bandchain --trust-node

networks:
  bandchain:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
