version: "3.5"

services:
  init1:
    image: odinprotocol/core:master
    container_name: init1
    command: /init-scripts/init.sh validator1
    volumes:
      - ./init-scripts:/init-scripts
      - vol1:/root/.odin
      - ./genesis.json:/genesis.json

  init2:
    image: odinprotocol/core:master
    container_name: init2
    depends_on:
      - init1
    command: /init-scripts/init.sh validator2
    volumes:
      - ./init-scripts:/init-scripts
      - vol2:/root/.odin
      - ./genesis.json:/genesis.json

  init3:
    image: odinprotocol/core:master
    container_name: init3
    depends_on:
      - init2
    command: /init-scripts/init.sh validator3
    volumes:
      - ./init-scripts:/init-scripts
      - vol3:/root/.odin
      - ./genesis.json:/genesis.json

  init4:
    image: odinprotocol/core:master
    container_name: init4
    depends_on:
      - init3
    command: /init-scripts/init.sh validator4
    volumes:
      - ./init-scripts:/init-scripts
      - vol4:/root/.odin
      - ./genesis.json:/genesis.json

  validator1:
    image: odinprotocol/core:master
    container_name: validator1
    depends_on:
      - init4
    networks:
      default:
        ipv4_address: 172.18.0.11
    command: odind start --rpc.laddr tcp://0.0.0.0:26657 --p2p.persistent_peers 11392b605378063b1c505c0ab123f04bd710d7d7@172.18.0.11:26656,0851086afcd835d5a6fb0ffbf96fcdf74fec742e@172.18.0.12:26656,63808bd64f2ec19acb2a494c8ce8467c595f6fba@172.18.0.14:26656,7b58b086dd915a79836eb8bfa956aeb9488d13b0@172.18.0.13:26656
    volumes:
      - vol1:/root/.odin

  validator2:
    container_name: validator2
    image: odinprotocol/core:master
    depends_on:
      - validator1
    networks:
      default:
        ipv4_address: 172.18.0.12
    command: odind start --rpc.laddr tcp://0.0.0.0:26657 --p2p.persistent_peers 11392b605378063b1c505c0ab123f04bd710d7d7@172.18.0.11:26656,0851086afcd835d5a6fb0ffbf96fcdf74fec742e@172.18.0.12:26656,63808bd64f2ec19acb2a494c8ce8467c595f6fba@172.18.0.14:26656,7b58b086dd915a79836eb8bfa956aeb9488d13b0@172.18.0.13:26656
    volumes:
      - vol2:/root/.odin

  validator3:
    container_name: validator3
    image: odinprotocol/core:master
    depends_on:
      - validator2
    networks:
      default:
        ipv4_address: 172.18.0.13
    command: odind start --rpc.laddr tcp://0.0.0.0:26657 --p2p.persistent_peers 11392b605378063b1c505c0ab123f04bd710d7d7@172.18.0.11:26656,0851086afcd835d5a6fb0ffbf96fcdf74fec742e@172.18.0.12:26656,63808bd64f2ec19acb2a494c8ce8467c595f6fba@172.18.0.14:26656,7b58b086dd915a79836eb8bfa956aeb9488d13b0@172.18.0.13:26656
    volumes:
      - vol3:/root/.odin

  validator4:
    container_name: validator4
    image: odinprotocol/core:master
    depends_on:
      - validator3
    networks:
      default:
        ipv4_address: 172.18.0.14
    command: odind start --rpc.laddr tcp://0.0.0.0:26657 --p2p.persistent_peers 11392b605378063b1c505c0ab123f04bd710d7d7@172.18.0.11:26656,0851086afcd835d5a6fb0ffbf96fcdf74fec742e@172.18.0.12:26656,63808bd64f2ec19acb2a494c8ce8467c595f6fba@172.18.0.14:26656,7b58b086dd915a79836eb8bfa956aeb9488d13b0@172.18.0.13:26656
    ports:
      - 26658:26658
      - 26657:26657
      - 26656:26656
      - 9090:9090
      - 1317:1317
    volumes:
      - vol4:/root/.odin

  faucet:
    container_name: faucet
    image: odinprotocol/core:master
    depends_on:
      - validator4
    networks:
      default:
        ipv4_address: 172.18.0.15
    command: sh -c "/utils/wait-for-account.sh && /init-scripts/faucet.sh supplier tcp://172.18.0.14:26657 && faucet run --node tcp://172.18.0.14:26657"
    ports:
      - 5005:5005
    volumes:
      - ./utils:/utils
      - ./init-scripts:/init-scripts

  executor:
    container_name: executor
    image: odinprotocol/core:master
    depends_on:
      - faucet
    networks:
      default:
        ipv4_address: 172.18.0.16
    command: sh -c "/utils/wait-for-service.sh && /init-scripts/entrypoint.sh supplier tcp://172.18.0.14:26657 && yoda run --log-level debug --node tcp://172.18.0.14:26657"
    volumes:
      - ./utils:/utils
      - ./init-scripts:/init-scripts
      - ./oracle-scripts:/oracle-scripts
      - ./data-source-scripts:/data-source-scripts

  odin-deposit-ether:
    image: odinprotocol/odin-deposit-ether:master
    environment:
      - CONFIG=/config.yaml
    volumes:
      - ./configs/odin-deposit-ether-config.yaml:/config.yaml
    restart: always
    command: odin-deposit-ether-svc run deposit

  odin-telemetry:
    image: odinprotocol/odin-telemetry:master
    environment:
      - KV_VIPER_FILE=/config.yaml
    depends_on:
      - odin-telemetry_db
    ports:
      - 8100:8100
    volumes:
      - ./configs/odin-telemetry-config.yaml:/config.yaml
    restart: always
    entrypoint: sh -c "odin-telemetry migrate up && odin-telemetry run service"

  odin-telemetry_db:
    image: tokend/postgres-ubuntu:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=telemetry
      - POSTGRES_PASSWORD=telemetry
      - POSTGRES_DB=telemetry
      - PGDATA=/pgdata
    volumes:
      - telemetry-data:/pgdata

volumes:
  vol1:
  vol2:
  vol3:
  vol4:
  database-data:
  telemetry-data:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"