listener:
  addr: :80

log:
  level: debug

binance:
  chain:
    endpoint: "https://api.bscscan.com/api"
  tokens:
    odin:
      address: "0xff8b00d90cc98a3be1c3e8f38fa0a200adb9e8f6"
      precision: 9
  api_key: "GMZGJPVP9HJ4Q7HE7V8H1FMMAXX48XHT37"


odin:
  chain:
    endpoint: "172.18.0.14:9090"
    chain_id: "odin"
    memo: ""
    gas_price: 10
    gas_limit: 500000
  signer:
    mnemonic: "prize weapon virus foot mandate finger add strong world physical token castle knee bracket armed quit brand physical neglect film tip okay view broken"
  exchange:
    denom: "loki"
    precision: 18

db:
  url: "postgres://postgres:postgres@bsc_db/postgres?sslmode=disable"